### ISSUE TITLE
Should the lock be global?

### ISSUE THREAD

**Issue by charleso** [ambiata/tatooine-cli#9]
If two daemons are running in parallel on the same machine:

```
2015-10-01 06:24:16 UTC - ERROR - Unable to lock /tmp/ambiata-upload.lock - is another process using it?
```

**Comment by nhibberd** [comment]
Haven't looked at the actually implementation, but this is definitely necessary for things like ci. However, in production a global lock completely makes sense. So probably the best solution is to make this a parameterized option

**Comment by charleso** [comment]
https://github.com/ambiata/tatooine-cli/pull/11
